services:
  api:
    build: .
    volumes:
      - "./settings.yaml:/app/settings.yaml:ro" # Read-only settings file
      - "data:/app/data"
    restart: always
    ports:
      - "8000:8000"
    environment:
      FORWARDED_ALLOW_IPS: "*"
      TZ: "Europe/Moscow"

volumes:
  data:
    driver: local
