services:
  api:
    build: .
    volumes:
      - "./settings.yaml:/app/settings.yaml:ro" # Read-only settings file
      - "data:/app/data"
    restart: always
    ports:
      - "8888:8080"
    environment:
      FORWARDED_ALLOW_IPS: "*"
      TZ: "Europe/Moscow"
      RECREATE_DATABASE: ${RECREATE_DATABASE:-false}
    deploy:
      # Change limits if project needs more RAM, though try to stay within limits
      resources:
        limits:
          memory: 1g
        reservations:
          memory: 500m

volumes:
  data:
    driver: local
