"""initial migration

Revision ID: 289e08d5b01f
Revises:
Create Date: 2025-11-09 19:54:08.062506
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "289e08d5b01f"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "patron",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("telegram_id", sa.String(), nullable=False),
        sa.Column("telegram_data", sa.JSON(), server_default="{}", nullable=False),
        sa.Column("is_admin", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_patron_telegram_id"), "patron", ["telegram_id"], unique=True)
    op.create_table(
        "timewindows",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("start", sa.Date(), nullable=False),
        sa.Column("end", sa.Date(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "applications",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("submitted_at", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False),
        sa.Column("session_id", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("full_name", sa.String(), nullable=False),
        sa.Column("cv", sa.String(), nullable=True),
        sa.Column("motivational_letter", sa.String(), nullable=True),
        sa.Column("recommendation_letter", sa.String(), nullable=True),
        sa.Column("transcript", sa.String(), nullable=True),
        sa.Column("almost_a_student", sa.String(), nullable=True),
        sa.Column("timewindow_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["timewindow_id"], ["timewindows.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_applications_email"), "applications", ["email"], unique=False)
    op.create_index(op.f("ix_applications_timewindow_id"), "applications", ["timewindow_id"], unique=False)
    op.create_table(
        "patron_daily_stats",
        sa.Column("date", sa.Date(), server_default=sa.text("(CURRENT_DATE)"), nullable=False),
        sa.Column("patron_id", sa.Integer(), nullable=False),
        sa.Column("rating_count", sa.Integer(), nullable=False),
        sa.Column("ranking_count", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["patron_id"], ["patron.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("date", "patron_id"),
    )
    op.create_index(op.f("ix_patron_daily_stats_patron_id"), "patron_daily_stats", ["patron_id"], unique=False)
    op.create_table(
        "patron_ranking",
        sa.Column("patron_id", sa.Integer(), nullable=False),
        sa.Column("application_id", sa.Integer(), nullable=False),
        sa.Column("rank", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False),
        sa.ForeignKeyConstraint(["application_id"], ["applications.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["patron_id"], ["patron.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("patron_id", "application_id"),
    )
    op.create_table(
        "patron_x_application",
        sa.Column("patron_id", sa.Integer(), nullable=False),
        sa.Column("application_id", sa.Integer(), nullable=False),
        sa.Column("docs", sa.JSON(), nullable=False),
        sa.Column("rate", sa.Enum("POSITIVE", "NEGATIVE", "NEUTRAL", "UNRATED", name="rating"), nullable=False),
        sa.Column("comment", sa.String(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False),
        sa.ForeignKeyConstraint(["application_id"], ["applications.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["patron_id"], ["patron.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("patron_id", "application_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("patron_x_application")
    op.drop_table("patron_ranking")
    op.drop_index(op.f("ix_patron_daily_stats_patron_id"), table_name="patron_daily_stats")
    op.drop_table("patron_daily_stats")
    op.drop_index(op.f("ix_applications_timewindow_id"), table_name="applications")
    op.drop_index(op.f("ix_applications_email"), table_name="applications")
    op.drop_table("applications")
    op.drop_table("timewindows")
    op.drop_index(op.f("ix_patron_telegram_id"), table_name="patron")
    op.drop_table("patron")
    # ### end Alembic commands ###
